name: 'Artifactory Publish Task'
description: 'Github Actions for publishing artifacts to artifactory.'
author: 'Linjith'
inputs: 
  includePattern:
    description: 'Include Pattern'
    default: ''
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.includePattern }}
